# -*- coding: utf-8 -*-
"""nlp_lab_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TXZP0PT5FEzLvWYCOgPkhS2wDWDGapTS
"""

!pip install rnnmorph

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
from nltk import sent_tokenize
from nltk.corpus import stopwords
nltk.download('stopwords')
import re

from google.colab import drive
drive.mount('/content/drive')
txt = open("/content/drive/MyDrive/text.txt")

text = txt.read()
text = re.sub(r'[^\w\s]', '', text)
stop_words = set(stopwords.words('russian'))
tokens = [token for token in word_tokenize(text) if token.lower() not in stop_words]

from rnnmorph.predictor import RNNMorphPredictor
predictor = RNNMorphPredictor(language='ru')
res = predictor.predict(tokens)

pairs = []
for i in range(len(res) - 1):
  tag1 = res[i].tag
  tag2 = res[i+1].tag
  if (((res[i].pos in ['NOUN', 'ADJ']) or (res[i+1].pos in ['NOUN', 'ADJ'])) and (res[i].tag == res[i+1].tag)):
    pairs.append((res[i].normal_form, res[i+1].normal_form))
for pair in pairs:
  print(f"{pair[0]}, {pair[1]}")